package com.julianavar.gdext
package godotscalanativelib.ffi.generators

import godotscalanativelib.utils.ScalaFile

object GdxFfiGenerator:
    def generate(interfaceNames: Vector[String], folder: String, file: String): Vector[ScalaFile] =
        Vector(ScalaFile(folder, file, procTable(interfaceNames)))

    def procTable(interfaceNames: Vector[String]): String =
        val varDecls = interfaceNames.map { name => s"    var $name: Ptr[Byte] = null" }
            .mkString("\n")

        val initAssigns = interfaceNames.map { name =>
            s"""        $name = getProcAddr(c"$name")"""
        }.mkString("\n")

        s"""// Generated by gdext.generator.core — do not edit.
               |package com.julianavar.gdext.ffi
               |
               |import scala.scalanative.unsafe.*
               |
               |private[gdext] object GdxFfi:
               |    // Mirrors GetProcAddressFn from gdext.core — same underlying type.
               |    type GetProcAddressFn = CFuncPtr1[CString, Ptr[Byte]]
               |
               |$varDecls
               |
               |    def initialize(getProcAddr: GetProcAddressFn): Unit =
               |$initAssigns
               |end GdxFfi
               |""".stripMargin
    end procTable
end GdxFfiGenerator
