package com.julianavar.gdext
package godotscalanativelib.ffi.generators

import godotscalanativelib.utils.ScalaFile

object TypesGenerator:

    def generate(typesJson: ujson.Value, folder: String, file: String): Vector[ScalaFile] =
        val lines = scala.collection.mutable.ArrayBuffer.empty[String]

        typesJson.arr.foreach { tp =>
            val name = tp("name").str
            tp("kind").str match
                case "alias" =>
                    val underlying = TypeMapper.scalaTypeName(tp("type").str)
                    lines += s"type $name = $underlying"

                case "handle" => lines += s"type $name = Ptr[Byte]"

                case "struct" =>
                    val members = tp.obj.get("members").map(_.arr.toSeq).getOrElse(Seq.empty)
                    if members.isEmpty || members.size > 22 then
                        // Opaque for empty or oversize structs; size hardcoded at call site.
                        lines += s"type $name = Ptr[Byte]"
                    else
                        val n          = members.size
                        val fieldTypes = members.map(m => TypeMapper.scalaTypeName(m("type").str))
                            .mkString(", ")
                        lines += s"type $name = CStruct$n[$fieldTypes]"
                        lines += s"given Tag[$name] = Tag.materializeCStruct${n}Tag[$fieldTypes]"
                    end if

                case "enum" =>
                    val isBitfield = tp.obj.get("is_bitfield").exists(_.bool)
                    val baseType   = if isBitfield then "CInt" else "CUnsignedInt"
                    val valLines   = tp("values").arr.map { v =>
                        val vName = v("name").str
                        val vVal  = v("value").num.toInt
                        val rhs   = if isBitfield then s"$vVal" else s"$vVal.toUInt"
                        s"    final val $vName: $name = $rhs"
                    }.mkString("\n")
                    lines += s"type $name = $baseType"
                    lines += s"object $name:\n$valLines"

                case "function" =>
                    val argTypes = tp("arguments").arr
                        .map(a => TypeMapper.scalaTypeName(a("type").str)).toSeq
                    val ret = tp.obj.get("return_value")
                        .map(r => TypeMapper.scalaTypeName(r("type").str)).getOrElse("Unit")
                    val cfp = s"CFuncPtr${argTypes.length}[${(argTypes :+ ret).mkString(", ")}]"
                    lines += s"type $name = $cfp"

                case _ => ()
            end match
        }

        val content = s"""|// Sys layer — C-ABI names. Not for game code; use gdext.api.* instead.
                |// Generated by gdext.generator.core — do not edit.
                |package com.julianavar.gdext.ffi
                |
                |import scala.scalanative.unsafe.*
                |import scala.scalanative.unsigned.*
                |import scala.scalanative.unsigned.UInt.*
                |
                |${lines.mkString("\n\n")}
                |""".stripMargin

        Vector(ScalaFile(folder, file, content))
    end generate
end TypesGenerator
