version = "3.11.0"
runner.dialect = "scala3"

align.preset = "more"
align.stripMargin = true

maxColumn = 100
indent.main = 4

// Recommended, to not penalize `match` statements
// indent.matchSite = 0

newlines.source = "fold"
// newlines.topLevelStatementBlankLines = [
//   {
//     minBreaks = 0
//     // blanks = 2
//   }
// ]


rewrite.scala3 = {
  convertToNewSyntax = true
  removeOptionalBraces.enabled = true
  insertEndMarkerMinLines = 4
}

fileOverride {
  "glob:**/gdext/generated/**" {
    rewrite.scala3.removeOptionalBraces.enabled = false
    rewrite.scala3.convertToNewSyntax = false
    rewrite.scala3.insertEndMarkerMinLines = 1000
    indent.main = 2
  }
}

fileOverride {
  "glob:**/examples/**" {
    newlines.annotation = false
  }
}
