package com.julianavar.gdext
package godotscalanativelib.api.generators

import scala.meta.*
import godotscalanativelib.resource_parser.Ast
import godotscalanativelib.utils.ScalaFile
import godotscalanativelib.utils.*

class GlobalScopeGenerator(using dialect: Dialect):
    def generate(
        utilities: Vector[Ast.UtilityFunction],
        enums: Vector[Ast.GlobalEnum],
        folder: String,
        file: String
    ): Vector[ScalaFile] = //
        Vector(ScalaFile(content = globalScopeSource(utilities, enums), path = folder, name = file))

    private def enumObject(e: Ast.GlobalEnum): Defn.Object =
        val vals: List[Stat] = e.values.map { (name, value) =>
            Defn.Val(
              List(Mod.Final()),
              List(Pat.Var(Term.Name(name))),
              Some(Type.Name("Int")),
              Lit.Int(value.toInt)
            )
        }.toList
        simpleObject(e.scalaName, vals)
    end enumObject

    def globalScopeSource(
        utilities: Vector[Ast.UtilityFunction],
        enums: Vector[Ast.GlobalEnum]
    ): String =
        val varargVoidFns = utilities.filter(fn => fn.isVararg && fn.returnTypeName == "void")
        val methodDefs: List[Defn.Def] = varargVoidFns.map { fn =>
            val name             = toCamel(fn.name)
            val strBuf           = Term.Name("strBuf")
            val varBuf           = Term.Name("varBuf")
            val argsArr          = Term.Name("argsArr")
            val body: List[Stat] = List(
              simpleValDef("strBuf", stackallocTerm(Type.Name("Byte"), Some(8))),
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("initGodotString")),
                List(strBuf, Term.Apply(Term.Name("toCString"), List(Term.Name("s"))))
              ),
              simpleValDef("varBuf", stackallocTerm(Type.Name("Byte"), Some(24))),
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("buildStringVariant")),
                List(varBuf, strBuf)
              ),
              simpleValDef("argsArr", stackallocTerm(ptrByte, Some(1))),
              derefAssign(argsArr, varBuf),
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("callUtilityFunction")),
                List(
                  Term.Select(
                    Term.Select(Term.Name("UtilityFunctions"), Term.Name("Binds")),
                    Term.Name(name)
                  ),
                  argsArr,
                  Lit.Int(1),
                  Lit.Null()
                )
              ),
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("destroyGodotString")),
                List(strBuf)
              )
            )
            val param = Term.Param(Nil, Term.Name("s"), Some(Type.Name("String")), None)
            Defn.Def(
              Nil,
              Term.Name(name),
              Nil,
              List(List(param)),
              Some(Type.Name("Unit")),
              zoneWrap(body)
            )
        }.toList

        val enumObjects: List[Stat] = enums.map(enumObject).toList

        "// Generated by gdext generator — do not edit.\n" + buildSource(
          "com.julianavar.gdext.generated",
          List("import scala.scalanative.unsafe.*", "import com.julianavar.gdext.core.GdxApi"),
          methodDefs ++ enumObjects
        )
    end globalScopeSource
end GlobalScopeGenerator
