package net.`julian-avar`.gdext.mill
package godotscalanativelib.api

import scala.meta.*
import godotscalanativelib.resource_parser.Ast
import godotscalanativelib.utils.*

class UtilitiesGenerator(using dialect: Dialect):
    def generate(
        utilities: Vector[Ast.UtilityFunction],
        valueBuiltins: Set[String],
        refcountedTypes: Set[String],
        folder: String,
        file: String
    ): Vector[ScalaFile] = Vector(ScalaFile(
      content = utilitySource(utilities, valueBuiltins, refcountedTypes),
      path = folder,
      name = file
    ))

    private def utilitySource(
        utilities: Vector[Ast.UtilityFunction],
        valueBuiltins: Set[String] = Set.empty,
        refcountedTypes: Set[String] = Set.empty
    ): String =
        val methodDefs: List[Defn.Def] = utilities.map { fn =>
            val name    = toCamel(fn.name)
            val reqArgs = if fn.isVararg then Vector.empty else fn.arguments.filterNot(_.hasDefault)
            val params: List[Term.Param] =
                if fn.isVararg then List(Term.Param(Nil, Term.Name("args"), Some(ptrPtrByte), None))
                else reqArgs.map(godotParam(_, valueBuiltins)).toList
            val (rAlloc, rRead) = retSetup(fn.returnTypeName, None, valueBuiltins, refcountedTypes)
            val retPtr: Term    =
                if rAlloc.isDefined then asInstanceOfTerm(Term.Name("_ret"), ptrByte)
                else Lit.Null()
            val callStat: Stat = Term.Apply(
              Term.Select(Term.Name("GdxApi"), Term.Name("callUtilityFunction")),
              List(
                Term.Select(Term.Name("Binds"), Term.Name(name)),
                Term.Name("_args"),
                Lit.Int(if fn.isVararg then -1 else fn.arguments.size),
                retPtr
              )
            )
            val body = setupArgStats(fn.arguments, valueBuiltins, fn.isVararg) ++ rAlloc.toList ++
                List(callStat) ++ rRead.toList
            val needsZone = !fn.isVararg &&
                reqArgs.exists(a => a.typeName == "String" || a.typeName == "StringName")
            val retType =
                if fn.returnTypeName == "void" then Type.Name("Unit")
                else godotType(fn.returnTypeName, None, valueBuiltins)
            Defn.Def(
              Nil,
              Term.Name(name),
              Nil,
              List(params),
              Some(retType),
              if needsZone then zoneWrap(body) else Term.Block(body)
            )
        }.toList

        val bindsStats: List[Stat] = utilities.map { fn =>
            lazyValDef(
              toCamel(fn.name),
              ptrByte,
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("getUtilityFunctionPtr")),
                List(cStr(fn.name), Lit.Long(fn.hash))
              )
            )
        }.toList

        val utilitiesObj =
            simpleObject("UtilityFunctions", simpleObject("Binds", bindsStats) :: methodDefs)

        val printed = buildSource(
          "net.`julian-avar`.gdext.generated",
          List(
            "import scala.scalanative.unsafe.*",
            "import scala.scalanative.unsigned.*",
            "import scala.scalanative.libc.stdlib.malloc",
            "import net.`julian-avar`.gdext.core.GdxApi",
            "import net.`julian-avar`.gdext.ffi.*"
          ),
          List(utilitiesObj)
        )
        // scalameta only preserves comments on the exact tree passed to `.syntax`; once these defs
        // become members of the enclosing companion object/`Pkg`, any comment attached to them
        // individually is discarded on reprint. So comments are collected as (marker, text) pairs
        // and spliced into the fully-printed file text at the very end via `injectComments`.
        val markers = utilities.map(fn => s"def ${toCamel(fn.name)}(" -> formatComment(fn.description, None))
            .toList
        "// Generated by gdext generator — do not edit.\n" + injectComments(printed, markers)
    end utilitySource
end UtilitiesGenerator
