package com.julianavar.gdext
package godotscalanativelib.core.generators

import godotscalanativelib.core.ScalaFile

/** Generates the concrete heap builtin wrappers — NodePath, StringName, and other 8-byte handle
  * types — into gdext.core (package com.julianavar.gdext.core, written to core/src/).
  *
  * Each type gets: a class with lifecycle (malloc/free + GdxApi init/destroy), factory methods, and
  * four typeclass given instances (ToVariant, FromVariant, ExportType, DefaultValue).
  */
object HeapBuiltinGenerator:

    // Per-type metadata. GdxApi function names match the hand-written GdxApi.scala.
    private case class HeapType(
        name: String,
        variantTypeName: String, // e.g. "VariantType.NodePath"
        handleBytes: Int,
        initFn: Option[String],           // GdxApi.initXxx — None if no init needed
        destroyFn: Option[String],        // GdxApi.destroyXxx — None if no destroy
        toScalaFn: Option[String],        // GdxApi.xxxToScala — None if not applicable
        buildVariantFn: String,           // GdxApi.buildXxxVariant
        extractVariantFn: String,         // GdxApi.extractXxxFromVariant
        extraApply: Option[String] = None // extra companion factory (e.g. fromString)
    )

    private val types = Vector(
      HeapType(
        name = "NodePath",
        variantTypeName = "VariantType.NodePath",
        handleBytes = 8,
        initFn = Some("initNodePath"),
        destroyFn = Some("destroyNodePath"),
        toScalaFn = Some("nodePathToScala"),
        buildVariantFn = "buildNodePathVariant",
        extractVariantFn = "extractNodePathFromVariant",
        extraApply = Some("fromString")
      ),
      HeapType(
        name = "StringName",
        variantTypeName = "VariantType.StringName",
        handleBytes = 8,
        initFn = Some("initStringNameFromStr"),
        destroyFn = Some("destroyStringName"),
        toScalaFn = Some("stringNameToScala"),
        buildVariantFn = "buildStringNameVariant",
        extractVariantFn = "extractStringNameFromVariant",
        extraApply = None
      )
    )

    def generate(folder: String): Vector[ScalaFile] = types
        .map(t => ScalaFile(folder, t.name, fileContent(t)))

    private def fileContent(t: HeapType): String =
        val initBlock = t.initFn match
            case Some(fn) => t.name match
                    case "NodePath" =>
                        // NodePath init needs a temporary GodotString buffer
                        s"""|    def apply(path: String): ${t.name} =
                            |        val h = malloc(${t.handleBytes}).asInstanceOf[Ptr[Byte]]
                            |        memset(h, 0, ${t.handleBytes}.toUSize)
                            |        Zone {
                            |            val strBuf = stackalloc[Byte](8)
                            |            memset(strBuf, 0, 8.toUSize)
                            |            GdxApi.initGodotString(strBuf, toCString(path))
                            |            GdxApi.${fn}(h, strBuf)
                            |            GdxApi.destroyGodotString(strBuf)
                            |        }
                            |        new ${t.name}(h)
                            |    end apply""".stripMargin
                    case _ => s"""|    def apply(s: String): ${t.name} =
                            |        val h = malloc(${t.handleBytes}).asInstanceOf[Ptr[Byte]]
                            |        memset(h, 0, ${t.handleBytes}.toUSize)
                            |        Zone { GdxApi.${fn}(h, s) }
                            |        new ${t.name}(h)
                            |    end apply""".stripMargin
            case None => ""

        val toScalaBody = t.toScalaFn.map(fn => s"GdxApi.$fn(handle)").getOrElse(""""""""")

        val hasToScala   = t.toScalaFn.isDefined
        val isEmptyCheck =
            if hasToScala then
                "\n    def isEmpty: Boolean          = handle == null || toScalaString.isEmpty"
            else ""
        val toScalaLine =
            if hasToScala then s"\n    def toScalaString: String     = $toScalaBody" else ""
        val toStringLine =
            if hasToScala then
                s"""\n    override def toString: String = s"${t.name}($${toScalaString})" """
            else ""

        val destroyLine = t.destroyFn match
            case Some(fn) => s"""|    def destroy(): Unit           = if handle != null then
                    |        GdxApi.$fn(handle)
                    |        free(handle)""".stripMargin
            case None => s"    def destroy(): Unit           = if handle != null then free(handle)"

        s"""// Generated by gdext.generator.core — do not edit.
            |package com.julianavar.gdext.core
            |
            |import scala.scalanative.unsafe.*
            |import scala.scalanative.unsafe.Size.intToSize
            |import scala.scalanative.unsigned.*
            |import scala.scalanative.libc.stdlib.{malloc, free}
            |import scala.scalanative.libc.string.memset
            |
            |final class ${t
              .name} private[core] (private[core] val handle: Ptr[Byte]):$toScalaLine$toStringLine$isEmptyCheck
            |$destroyLine
            |end ${t.name}
            |
            |object ${t.name}:
            |$initBlock
            |
            |    def fromHandle(ptr: Ptr[Byte]): ${t.name} = new ${t.name}(ptr)
            |
            |    def empty: ${t.name} =
            |        val h = malloc(${t.handleBytes}).asInstanceOf[Ptr[Byte]]
            |        memset(h, 0, ${t.handleBytes}.toUSize)
            |        new ${t.name}(h)
            |    end empty
            |
            |    given ToVariant[${t.name}]:
            |        def variantType                                        = ${t.variantTypeName}
            |        def write(dest: Ptr[Byte], value: ${t.name}): Unit =
            |            memset(dest, 0, 24.toUSize)
            |            if value != null && value.handle != null then
            |                GdxApi.${t.buildVariantFn}(dest, value.handle)
            |        end write
            |    end given
            |
            |    given FromVariant[${t.name}]:
            |        def read(src: Ptr[Byte]): ${t.name} =
            |            val h = malloc(${t.handleBytes}).asInstanceOf[Ptr[Byte]]
            |            memset(h, 0, ${t.handleBytes}.toUSize)
            |            if src != null then GdxApi.${t.extractVariantFn}(src, h)
            |            new ${t.name}(h)
            |        end read
            |    end given
            |
            |    given ExportType[${t.name}]:
            |        def variantType                                        = ${t.variantTypeName}
            |        override def hint       = PropertyHint.None
            |        override def hintString = ""
            |        override def className  = ""
            |        override def usage      = PropertyUsage.Default
            |        def write(dest: Ptr[Byte], value: ${t.name}): Unit =
            |            memset(dest, 0, 24.toUSize)
            |            if value != null && value.handle != null then
            |                GdxApi.${t.buildVariantFn}(dest, value.handle)
            |        end write
            |        def read(src: Ptr[Byte]): ${t.name} =
            |            val h = malloc(${t.handleBytes}).asInstanceOf[Ptr[Byte]]
            |            memset(h, 0, ${t.handleBytes}.toUSize)
            |            if src != null then GdxApi.${t.extractVariantFn}(src, h)
            |            new ${t.name}(h)
            |        end read
            |    end given
            |
            |    given DefaultValue[${t.name}]:
            |        def default: ${t.name} = ${t.name}.empty
            |    end given
            |end ${t.name}
            |""".stripMargin
    end fileContent
end HeapBuiltinGenerator
