package gdext.generator
package trees

import scala.meta.*
import parser.Ast

class UtilitiesGenerator(using dialect: Dialect):
    def generate(
        utilities: Vector[Ast.UtilityFunction],
        valueBuiltins: Set[String],
        refcountedTypes: Set[String]
    ): Vector[ScalaFile] = Vector(ScalaFile(
      content = utilitySource(utilities, valueBuiltins, refcountedTypes),
      path = "gdext/generated",
      name = "UtilityFunctions"
    ))

    private def utilitySource(
        utilities: Vector[Ast.UtilityFunction],
        valueBuiltins: Set[String] = Set.empty,
        refcountedTypes: Set[String] = Set.empty
    ): String =
        val methodDefs: List[Defn.Def] = utilities.map { fn =>
            val name    = toCamel(fn.name)
            val reqArgs = if fn.isVararg then Vector.empty else fn.arguments.filterNot(_.hasDefault)
            val params: List[Term.Param] =
                if fn.isVararg then List(Term.Param(Nil, Term.Name("args"), Some(ptrPtrByte), None))
                else reqArgs.map(godotParam(_, valueBuiltins)).toList
            val (rAlloc, rRead) = retSetup(fn.returnTypeName, None, valueBuiltins, refcountedTypes)
            val retPtr: Term    =
                if rAlloc.isDefined then asInstanceOfTerm(Term.Name("_ret"), ptrByte)
                else Lit.Null()
            val callStat: Stat = Term.Apply(
              Term.Select(Term.Name("GdxApi"), Term.Name("callUtilityFunction")),
              List(
                Term.Select(Term.Name("Binds"), Term.Name(name)),
                Term.Name("_args"),
                Lit.Int(if fn.isVararg then -1 else fn.arguments.size),
                retPtr
              )
            )
            val body = setupArgStats(fn.arguments, valueBuiltins, fn.isVararg) ++ rAlloc.toList ++
                List(callStat) ++ rRead.toList
            val needsZone = !fn.isVararg &&
                reqArgs.exists(a => a.typeName == "String" || a.typeName == "StringName")
            val retType =
                if fn.returnTypeName == "void" then Type.Name("Unit")
                else godotType(fn.returnTypeName, None, valueBuiltins)
            Defn.Def(
              Nil,
              Term.Name(name),
              Nil,
              List(params),
              Some(retType),
              if needsZone then zoneWrap(body) else Term.Block(body)
            )
        }.toList

        val bindsStats: List[Stat] = utilities.map { fn =>
            lazyValDef(
              toCamel(fn.name),
              ptrByte,
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("getUtilityFunctionPtr")),
                List(cStr(fn.name), Lit.Long(fn.hash))
              )
            )
        }.toList

        val utilitiesObj =
            simpleObject("UtilityFunctions", simpleObject("Binds", bindsStats) :: methodDefs)

        "// Generated by gdext generator — do not edit.\n" + buildSource(
          "gdext.generated",
          List(
            "import scala.scalanative.unsafe.*",
            "import scala.scalanative.unsigned.*",
            "import gdext.core.GdxApi"
          ),
          List(utilitiesObj)
        )
    end utilitySource
end UtilitiesGenerator
