package gdext.generator
package trees

import scala.meta.*
import parser.Ast

class VirtualsGenerator(using dialect: Dialect):
    def generate(classes: Vector[Ast.GodotClass], valueBuiltins: Set[String]): Vector[ScalaFile] =
        val byName = classes.map(c => c.name -> c).toMap

        def allVirtualsWithOwner(cls: Ast.GodotClass): Vector[(Ast.GodotMethod, String)] =
            val own            = cls.methods.filter(_.isVirtual).map(_ -> cls.name)
            val parentVirtuals = cls.inherits.flatMap(byName.get).map(allVirtualsWithOwner)
                .getOrElse(Vector.empty)
            val ownNames = own.map(_._1.name).toSet
            parentVirtuals.filterNot(v => ownNames.contains(v._1.name)) ++ own
        end allVirtualsWithOwner

        // Every class gets a Virtuals file — even those with no overridable virtuals.
        // Register.auto[T] does Symbol.requiredModule(s"gdext.generated.${baseName}Virtuals")
        // at compile time, so the module must exist for every possible base class.
        classes.map { cls =>
            val virtuals = allVirtualsWithOwner(cls)
            val entries  = virtualEntryTerms(virtuals, valueBuiltins)
            ScalaFile(
              content = virtualsSource(cls, entries),
              path = "gdext/generated/virtuals",
              name = s"${cls.name}Virtuals"
            )
        }
    end generate

    private def virtualEntryTerms(
        virtuals: Vector[(Ast.GodotMethod, String)],
        valueBuiltins: Set[String]
    ): Vector[Term] = virtuals.flatMap { (m, defClass) =>
        val camelName         = toCamel(m.name)
        val retType           = godotTypeStr(m.returnTypeName, m.returnMeta, valueBuiltins)
        val conflictsWithBase = godotClassVirtuals.get(camelName).exists(_._1 != retType)
        if conflictsWithBase then None
        else
            val dispatch = buildDispatchLambda(m, defClass, valueBuiltins)
            val entryStr = s"""VirtualEntry("${m.name}", required = ${m
                    .isRequired}, dispatch = ${dispatch.syntax})"""
            Some(entryStr.parse[Term].get)
        end if
    }

    private def virtualsSource(cls: Ast.GodotClass, entries: Vector[Term]): String =
        val entriesValDef = Defn.Val(
          Nil,
          List(Pat.Var(Term.Name("entries"))),
          Some(Type.Apply(Type.Name("Vector"), List(Type.Name("VirtualEntry")))),
          Term.Apply(Term.Name("Vector"), entries.toList)
        )
        val objDef = simpleObject(s"${cls.name}Virtuals", List(entriesValDef))
        "// Generated by gdext generator — do not edit.\n" + buildSource(
          "gdext.generated",
          List(
            "import gdext.core.virtual.VirtualEntry",
            "import gdext.core.GodotObject",
            "import scala.scalanative.unsafe.*"
          ),
          List(objDef)
        )
    end virtualsSource
end VirtualsGenerator
