package com.`julian-avar`.gdext
package godotscalanativelib.ffi.generators

import godotscalanativelib.utils.ScalaFile

/** Generates CStruct23–CStruct26 opaque types and their Tags.scala materializers into gdext.ffi.
  * These extend Scala Native's CStruct22 maximum by composition.
  */
object CStructExtGenerator:

    def generate(folder: String): Vector[ScalaFile] =
        val cstructFiles = (23 to 26).toVector
            .map(n => ScalaFile(folder, s"CStruct$n", cstructFile(n)))
        cstructFiles :+ ScalaFile(folder, "Tags", tagsFile())
    end generate

    private def tps(n: Int): String    = (1 to n).map(i => s"T$i").mkString(", ")
    private def tagCs(n: Int): String  = (1 to n).map(i => s"Tag[T$i]").mkString(", ")
    private def tagCDs(n: Int): String = (1 to n).map(i => s"T$i: Tag").mkString(", ")

    private def cstructFile(n: Int): String =
        val p          = n - 1 // previous N
        val prevTpsStr = tps(p)
        val allTpsStr  = tps(n)
        val allTagCDs  = tagCDs(n)
        val allTagCs   = tagCs(n)

        val prevCStruct = if p == 22 then s"CStruct22[$prevTpsStr]" else s"CStruct$p[$prevTpsStr]"

        val getters = (1 to n).map { i =>
            val body = if i < n then s"struct._1._$i" else s"struct._2"
            s"    inline def _$i(using $allTagCs): T$i = $body"
        }.mkString("\n")

        val setters = (1 to n).map { i =>
            val body = if i < n then s"struct._1._${i}_=(value)" else s"struct._2 = value"
            s"    inline def _${i}_=(value: T$i)(using $allTagCs): Unit = $body"
        }.mkString("\n")

        val ats = (1 to n).map { i =>
            val body = if i < n then s"struct._1.at$i" else s"struct.at2"
            s"    inline def at$i(using $allTagCs): Ptr[T$i] = $body"
        }.mkString("\n")

        s"""// format: off
            |// Generated by gdext.generator.core — do not edit.
            |package com.`julian-avar`.gdext.ffi
            |
            |import scala.scalanative.unsafe.*
            |
            |import Tags.*
            |
            |opaque type CStruct$n[$allTpsStr] = CStruct2[$prevCStruct, T$n]
            |
            |object CStruct$n {
            |  inline given [$allTagCDs] => Tag[CStruct$n[$allTpsStr]] = materializeCStruct${n}Tag[$allTpsStr]
            |
            |  extension [$allTpsStr](struct: CStruct$n[$allTpsStr]) {
            |$getters
            |$setters
            |$ats
            |  }
            |}
            |// format: on""".stripMargin
    end cstructFile

    private def tagsFile(): String =
        val defs = (23 to 26).map { n =>
            val p           = n - 1
            val allTpsStr   = tps(n)
            val prevTpsStr  = tps(p)
            val allTagCDs   = tagCDs(n)
            val prevCStruct =
                if p == 22 then s"CStruct22[$prevTpsStr]" else s"CStruct$p[$prevTpsStr]"
            val prevMat =
                if p == 22 then s"Tag.materializeCStruct22Tag[$prevTpsStr]"
                else s"materializeCStruct${p}Tag[$prevTpsStr]"

            s"""  // CStruct$n = CStruct2[CStruct$p[T1..T$p], T$n]
                |  def materializeCStruct${n}Tag[$allTagCDs]: Tag[CStruct$n[$allTpsStr]] =
                |    Tag.materializeCStruct2Tag[$prevCStruct, T$n](
                |      using $prevMat,
                |      summon[Tag[T$n]]
                |    ).asInstanceOf[Tag[CStruct$n[$allTpsStr]]]""".stripMargin
        }.mkString("\n\n")

        s"""// format: off
            |// Generated by gdext.generator.core — do not edit.
            |package com.`julian-avar`.gdext.ffi
            |
            |import scala.scalanative.unsafe.*
            |
            |object Tags {
            |  private val voidPtrTag: Tag[CVoidPtr] = Tag.Byte.asInstanceOf[Tag[CVoidPtr]]
            |  def funcPtrTag[T]: Tag[T] = voidPtrTag.asInstanceOf[Tag[T]]
            |
            |$defs
            |}
            |// format: on""".stripMargin
    end tagsFile
end CStructExtGenerator
