package com.`julian-avar`.gdext
package godotscalanativelib.ffi.generators

import godotscalanativelib.utils.ScalaFile

object InterfaceGenerator:

    private def toPascalCase(snakeName: String): String = snakeName.split("_").map(_.capitalize)
        .mkString

    def generate(interfacesJson: ujson.Value, folder: String, file: String): Vector[ScalaFile] =
        val lines = interfacesJson.arr.map { iface =>
            val name     = iface("name").str
            val typeName = s"GDExtensionInterface${toPascalCase(name)}"
            val argTypes = iface("arguments").arr.map(a => TypeMapper.scalaTypeName(a("type").str))
                .toSeq
            val ret = iface.obj.get("return_value")
                .map(r => TypeMapper.scalaTypeName(r("type").str)).getOrElse("Unit")
            val cfp = s"CFuncPtr${argTypes.length}[${(argTypes :+ ret).mkString(", ")}]"
            s"type $typeName = $cfp"
        }.toVector

        val content = s"""|//  layer — C-ABI names. Not for game code; use gdext.api.* instead.
                |// Generated by gdext.generator.core — do not edit.
                |package com.`julian-avar`.gdext.ffi
                |
                |import scala.scalanative.unsafe.*
                |import scala.scalanative.unsigned.*
                |
                |${lines.mkString("\n\n")}
                |""".stripMargin

        Vector(ScalaFile(folder, file, content))
    end generate
end InterfaceGenerator
