package com.`julian-avar`.gdext
package godotscalanativelib.core.generators

import godotscalanativelib.core.ScalaFile

/** Generates PackedArrays.scala (package com.`julian-avar`.gdext.core) — bare PackedXxxArray handle
  * wrappers and extension methods on them.
  */
object PackedArraysGenerator:

    private case class PackedType(
        name: String,            // e.g. "PackedByteArray"
        vtConst: String,         // e.g. "VT_PACKED_BYTE"
        vtCode: Int,             // e.g. 29
        elemType: String,        // Scala element type, e.g. "Byte"
        indexFnVar: String,      // GdxApi var name, e.g. "packedByteArrayIndexFn"
        elemRead: String,        // how to read the element from the returned Ptr, e.g. "!ptr"
        zeroVal: String,         // zero/default for the element type
        hasApply: Boolean = true // false for Vec2/3/4/Color (apply in generated layer)
    )

    def generate(folder: String, file: String): Vector[ScalaFile] =
        val content = buildFile()
        Vector(ScalaFile(folder, file, content))

    private val types = Vector(
      PackedType(
        "PackedByteArray",
        "VT_PACKED_BYTE",
        29,
        "Byte",
        "packedByteArrayIndexFn",
        "!fn(a.ptr, i.toLong)",
        "0.toByte"
      ),
      PackedType(
        "PackedInt32Array",
        "VT_PACKED_INT32",
        30,
        "Int",
        "packedInt32ArrayIndexFn",
        "!fn(a.ptr, i.toLong).asInstanceOf[Ptr[Int]]",
        "0"
      ),
      PackedType(
        "PackedInt64Array",
        "VT_PACKED_INT64",
        31,
        "Long",
        "packedInt64ArrayIndexFn",
        "!fn(a.ptr, i.toLong).asInstanceOf[Ptr[Long]]",
        "0L"
      ),
      PackedType(
        "PackedFloat32Array",
        "VT_PACKED_FLOAT32",
        32,
        "Float",
        "packedFloat32ArrayIndexFn",
        "!fn(a.ptr, i.toLong).asInstanceOf[Ptr[Float]]",
        "0f"
      ),
      PackedType(
        "PackedFloat64Array",
        "VT_PACKED_FLOAT64",
        33,
        "Double",
        "packedFloat64ArrayIndexFn",
        "!fn(a.ptr, i.toLong).asInstanceOf[Ptr[Double]]",
        "0.0"
      ),
      PackedType(
        "PackedStringArray",
        "VT_PACKED_STRING",
        34,
        "String",
        "packedStringArrayIndexFn",
        "{ val p = fn(a.ptr, i.toLong); if p == null then \"\" else GdxApi.godotStringToScala(p) }",
        "\"\""
      ),
      PackedType(
        "PackedVector2Array",
        "VT_PACKED_VEC2",
        35,
        "Vector2",
        "",
        "",
        "",
        hasApply = false
      ),
      PackedType(
        "PackedVector3Array",
        "VT_PACKED_VEC3",
        36,
        "Vector3",
        "",
        "",
        "",
        hasApply = false
      ),
      PackedType(
        "PackedVector4Array",
        "VT_PACKED_VEC4",
        38,
        "Vector4",
        "",
        "",
        "",
        hasApply = false
      ),
      PackedType("PackedColorArray", "VT_PACKED_COLOR", 37, "Color", "", "", "", hasApply = false)
    )

    private def buildFile(): String =
        val vtConsts = types.distinctBy(_.vtConst).map { t =>
            s"private inline val ${t.vtConst} = ${t.vtCode}"
        }.mkString("\n")

        // Bare handle wrappers — a packed array is a single 8-byte cowdata pointer in the ABI,
        // same shape as RID/Callable. Extension methods below operate on `.ptr` directly.
        val classes = types.map(t => s"final class ${t.name}(val ptr: Ptr[Byte])").mkString("\n")

        val extensions = types.map(buildExtension).mkString("\n\n")

        s"""// Generated by gdext.generator.core — do not edit.
            |package com.`julian-avar`.gdext.core
            |
            |import scala.scalanative.unsafe.*
            |import scala.scalanative.unsigned.*
            |
            |$classes
            |
            |// ── Shared size helper ──────────────────────────────────────────────────────
            |private def packedArraySize(arr: Ptr[Byte], typeId: Int): Int =
            |    val fn = GdxApi.packedSizeFns(typeId)
            |    if arr == null || fn == null then return 0
            |    val ret = stackalloc[Long]()
            |    val callFn = CFuncPtr.fromPtr[CFuncPtr4[Ptr[Byte], Ptr[Ptr[Byte]], Ptr[Byte], CInt, Unit]](fn)
            |    callFn(arr, null, ret.asInstanceOf[Ptr[Byte]], 0)
            |    (!ret).toInt
            |end packedArraySize
            |
            |$vtConsts
            |
            |$extensions
            |""".stripMargin
    end buildFile

    private def buildExtension(t: PackedType): String =
        val sizeLine = s"def size: Int = packedArraySize(a.ptr, ${t.vtConst})"

        val applyBlock =
            if !t.hasApply then ""
            else
                s"""
                |    def apply(i: Int): ${t.elemType} =
                |        val fn = GdxApi.${t.indexFnVar}
                |        if a.ptr == null || fn == null then return ${t.zeroVal}
                |        ${t.elemRead}
                |    end apply
                |
                |    def toArray: Array[${t.elemType}] =
                |        val n   = a.size
                |        val buf = new Array[${t.elemType}](n)
                |        var i   = 0
                |        while i < n do buf(i) = a.apply(i); i += 1
                |        buf
                |    end toArray"""

        s"""extension (a: ${t.name})
            |    $sizeLine$applyBlock
            |end extension"""
    end buildExtension
end PackedArraysGenerator
