package com.`julian-avar`.gdext
package godotscalanativelib.api.generators

import scala.meta.*
import godotscalanativelib.resource_parser.Ast
import godotscalanativelib.resource_parser.Parser
import godotscalanativelib.utils.*

class TypesGenerator(using dialect: Dialect):
    def generate(types: Vector[Ast.Type], folder: String): Vector[ScalaFile] = types
        .groupBy(_.kind.name).map { (name, ts) =>
            ScalaFile(content = typesSource(name, ts), path = folder, name = name)
        }.toVector

    private def typesSource(kindName: String, types: Vector[Ast.Type]): String =
        def withComment(comment: String, stat: Stat): Stat =
            if comment.nonEmpty then s"$comment\n${stat.syntax}".parse[Stat].get else stat

        val stats: List[Stat] = types.flatMap { tp =>
            val comment = formatComment(tp)
            tp.kind match
                case Ast.Kind.Alias(underlying) =>
                    val rhs = Parser.typeName(underlying).parse[Type].get
                    List(withComment(
                      comment,
                      Defn.Type(Nil, Type.Name(tp.name), Nil, rhs, Type.Bounds(None, None))
                    ))
                case Ast.Kind.Handle(_, _, _) => List(withComment(
                      comment,
                      Defn.Type(Nil, Type.Name(tp.name), Nil, ptrByte, Type.Bounds(None, None))
                    ))
                case Ast.Kind.Enum(values, isBitfield) =>
                    val baseType = if isBitfield then "CInt" else "CUnsignedInt"
                    val typeDef  = Defn.Type(
                      Nil,
                      Type.Name(tp.name),
                      Nil,
                      Type.Name(baseType),
                      Type.Bounds(None, None)
                    )
                    val valStats: List[Stat] = values.sortBy(_.index).map { v =>
                        val rhs: Term =
                            if isBitfield then Lit.Int(v.index)
                            else Term.Select(Lit.Int(v.index), Term.Name("toUInt"))
                        Defn.Val(
                          List(Mod.Final()),
                          List(Pat.Var(Term.Name(v.name))),
                          Some(Type.Name(tp.name)),
                          rhs
                        )
                    }.toList
                    List(withComment(comment, typeDef), simpleObject(tp.name, valStats))
                case Ast.Kind.Struct(_) => List(withComment(
                      comment,
                      Defn.Type(Nil, Type.Name(tp.name), Nil, ptrByte, Type.Bounds(None, None))
                    ))
                case Ast.Kind.Function(args, ret) => List(
                      withComment(comment, functionDefStat(tp.name, Ast.Kind.Function(args, ret)))
                    )
            end match
        }.toList

        "// Generated by gdext generator — do not edit.\n" + buildSource(
          "com.julian-avar.gdext.generated.types",
          List(
            "import scala.scalanative.unsafe.*",
            "import scala.scalanative.unsigned.*",
            "import scala.scalanative.unsigned.UInt.*"
          ),
          stats
        )
    end typesSource
end TypesGenerator
