package net.`julian-avar`.gdext
package godotscalanativelib.api.generators

import scala.meta.*
import godotscalanativelib.resource_parser.Ast
import godotscalanativelib.utils.ScalaFile
import godotscalanativelib.utils.*

class GlobalScopeGenerator(using dialect: Dialect):
    def generate(
        utilities: Vector[Ast.UtilityFunction],
        enums: Vector[Ast.GlobalEnum],
        folder: String,
        file: String
    ): Vector[ScalaFile] = //
        Vector(ScalaFile(content = globalScopeSource(utilities, enums), path = folder, name = file))

    private def enumObject(e: Ast.GlobalEnum): Defn.Object =
        val vals: List[Stat] = e.values.map { (name, value, _) =>
            Defn.Val(
              List(Mod.Final()),
              List(Pat.Var(Term.Name(name))),
              Some(Type.Name("Int")),
              Lit.Int(value.toInt)
            )
        }.toList
        simpleObject(e.scalaName, vals)
    end enumObject

    def globalScopeSource(
        utilities: Vector[Ast.UtilityFunction],
        enums: Vector[Ast.GlobalEnum]
    ): String =
        val varargVoidFns = utilities.filter(fn => fn.isVararg && fn.returnTypeName == "void")
        val methodDefs: List[Defn.Def] = varargVoidFns.map { fn =>
            val name             = toCamel(fn.name)
            val strBuf           = Term.Name("strBuf")
            val varBuf           = Term.Name("varBuf")
            val argsArr          = Term.Name("argsArr")
            val body: List[Stat] = List(
              simpleValDef("strBuf", stackallocTerm(Type.Name("Byte"), Some(8))),
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("initGodotString")),
                List(strBuf, Term.Apply(Term.Name("toCString"), List(Term.Name("s"))))
              ),
              simpleValDef("varBuf", stackallocTerm(Type.Name("Byte"), Some(24))),
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("buildStringVariant")),
                List(varBuf, strBuf)
              ),
              simpleValDef("argsArr", stackallocTerm(ptrByte, Some(1))),
              derefAssign(argsArr, varBuf),
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("callUtilityFunction")),
                List(
                  Term.Select(
                    Term.Select(Term.Name("UtilityFunctions"), Term.Name("Binds")),
                    Term.Name(name)
                  ),
                  argsArr,
                  Lit.Int(1),
                  Lit.Null()
                )
              ),
              Term.Apply(
                Term.Select(Term.Name("GdxApi"), Term.Name("destroyGodotString")),
                List(strBuf)
              )
            )
            val param = Term.Param(Nil, Term.Name("s"), Some(Type.Name("String")), None)
            Defn.Def(
              Nil,
              Term.Name(name),
              Nil,
              List(List(param)),
              Some(Type.Name("Unit")),
              zoneWrap(body)
            )
        }.toList

        val enumObjects: List[Stat] = enums.map(enumObject).toList

        val printed = buildSource(
          "net.`julian-avar`.gdext.generated",
          List("import scala.scalanative.unsafe.*", "import net.`julian-avar`.gdext.core.GdxApi"),
          methodDefs ++ enumObjects
        )

        // scalameta only preserves comments on the exact tree passed to `.syntax`; once these defs
        // become members of the enclosing `Pkg`, any comment attached to them individually is
        // discarded on reprint. So comments are collected as (marker, text) pairs here and spliced
        // into the fully-printed file text at the very end via `injectComments`.
        //
        // Enum value names (e.g. `NONE`) repeat across different enums sharing this one file, and
        // `injectComments` resolves repeated markers by consuming successive occurrences in list
        // order -- so each enum's values must stay in the same order they're emitted above.
        val methodMarkers = varargVoidFns.map(fn =>
            s"def ${toCamel(fn.name)}(" -> formatComment(fn.description, None)
        ).toList
        val enumValueMarkers = enums.flatMap { e =>
            e.values.flatMap { (name, _, desc) =>
                desc.map(d => s"val $name:" -> formatComment(Some(d), None))
            }
        }.toList
        "// Generated by gdext generator — do not edit.\n" +
            injectComments(printed, methodMarkers ++ enumValueMarkers)
    end globalScopeSource
end GlobalScopeGenerator
