package net.`julian-avar`.gdext
package godotscalanativelib.api.generators

import scala.meta.*
import godotscalanativelib.resource_parser.Ast
import godotscalanativelib.utils.*

class InterfacesGenerator(using dialect: Dialect):
    def generate(
        interfaces: Vector[Ast.Interface],
        folder: String,
        file: String
    ): Vector[ScalaFile] =
        Vector(ScalaFile(content = interfaceSource(interfaces), path = folder, name = file))

    private def interfaceSource(interfaces: Vector[Ast.Interface]): String =
        def getInterfaceName(fromName: String) =
            s"GDExtensionInterface${fromName.split("_").map(_.capitalize).mkString}"

        // See the note in TypesGenerator: comments have to be spliced into the printed text via
        // `injectComments` rather than attached to the tree, since scalameta drops them once these
        // defs become members of the enclosing `Pkg`.
        val ifaceMarkers: List[(String, String)] = interfaces.map { iface =>
            s"type ${getInterfaceName(iface.name)} =" -> formatComment(iface.description, iface.deprecated)
        }.toList

        val typeDefs: List[Stat] = interfaces.map { iface =>
            functionDefStat(getInterfaceName(iface.name), Ast.Kind.Function(iface.arguments, iface.returnValue))
        }.toList

        val varFields: List[Stat] = interfaces.map { iface =>
            val tn = getInterfaceName(iface.name)
            buildVarDef(iface.name, Type.Name(tn), asInstanceOfTerm(Lit.Null(), Type.Name(tn)))
        }.toList

        val interfaceClass = Defn.Class(
          Nil,
          Type.Name("Interface"),
          Nil,
          Ctor.Primary(List(Mod.Private(Name.Anonymous())), Name.Anonymous(), List(Nil)),
          emptyTemplate(varFields)
        )

        val batchSize = 20
        val batches   = interfaces.grouped(batchSize).toVector

        val resultParam = Term.Param(Nil, Term.Name("result"), Some(Type.Name("Interface")), None)
        val getProcAddrParam = Term.Param(
          Nil,
          Term.Name("getProcAddr"),
          Some(Type.Name("GDExtensionInterfaceGetProcAddress")),
          None
        )
        val zoneParam = buildUsingParam("zone", Type.Name("Zone"))

        val helperMethods: List[Defn.Def] = batches.zipWithIndex.map { (batch, idx) =>
            val bodyStats: List[Stat] = batch.map { iface =>
                val tn = getInterfaceName(iface.name)
                Term.Assign(
                  Term.Select(Term.Name("result"), Term.Name(iface.name)),
                  asInstanceOfTerm(
                    Term.Apply(
                      Term.Select(Term.Name("getProcAddr"), Term.Name("apply")),
                      List(Term.Apply(Term.Name("toCString"), List(Lit.String(iface.name))))
                    ),
                    Type.Name(tn)
                  )
                )
            }.toList
            Defn.Def(
              List(Mod.Private(Name.Anonymous())),
              Term.Name(s"loadBatch$idx"),
              Nil,
              List(List(resultParam, getProcAddrParam), List(zoneParam)),
              Some(Type.Name("Unit")),
              Term.Block(bodyStats)
            )
        }.toList

        val loadCalls: List[Stat] = batches.indices.map { i =>
            Term.Apply(
              Term.Name(s"loadBatch$i"),
              List(Term.Name("result"), Term.Name("getProcAddr"))
            )
        }.toList

        val givenZone = buildGivenAlias(Type.Name("Zone"), Term.Name("zone"))
        val newResult = simpleValDef(
          "result",
          Term.New(Init(Type.Name("Interface"), Name.Anonymous(), List(Nil)))
        )
        val acquireLambda = Term.Function(
          List(Term.Param(Nil, Term.Name("zone"), Some(Type.Name("Zone")), None)),
          Term.Block(List(givenZone, newResult) ++ loadCalls :+ Term.Name("result"))
        )
        val loadMethod = Defn.Def(
          Nil,
          Term.Name("load"),
          Nil,
          List(List(Term.Param(
            Nil,
            Term.Name("getProcAddr"),
            Some(Type.Name("GDExtensionInterfaceGetProcAddress")),
            None
          ))),
          Some(Type.Name("Interface")),
          Term.Apply(Term.Select(Term.Name("Zone"), Term.Name("acquire")), List(acquireLambda))
        )

        val companionObj = simpleObject("Interface", helperMethods :+ loadMethod)

        val printed = buildSource(
          "net.`julian-avar`.gdext.generated",
          List(
            "import scala.scalanative.unsafe.*",
            "import scala.scalanative.unsigned.*",
            "import scala.scalanative.unsigned.UInt.*",
            "import net.`julian-avar`.gdext.generated.types.*"
          ),
          typeDefs ++ List(interfaceClass, companionObj)
        )
        "// Generated by gdext generator — do not edit.\n" + injectComments(printed, ifaceMarkers)
    end interfaceSource
end InterfacesGenerator
