package net.`julian-avar`.gdext
package godotscalanativelib.api.generators

import scala.meta.*
import godotscalanativelib.resource_parser.Ast
import godotscalanativelib.resource_parser.Parser
import godotscalanativelib.utils.*

class TypesGenerator(using dialect: Dialect):
    def generate(types: Vector[Ast.Type], folder: String): Vector[ScalaFile] = types
        .groupBy(_.kind.name).map { (name, ts) =>
            ScalaFile(content = typesSource(name, ts), path = folder, name = name)
        }.toVector

    private def typesSource(kindName: String, types: Vector[Ast.Type]): String =
        // scalameta only preserves comments on the exact tree passed to `.syntax`; once these defs
        // become members of the enclosing `Pkg`, any comment attached to them individually is
        // discarded on reprint. So comments are collected as (marker, text) pairs here and spliced
        // into the fully-printed file text at the very end via `injectComments`.
        val markers = types.map(tp => s"type ${tp.name} =" -> formatComment(tp)).toList

        val stats: List[Stat] = types.flatMap { tp =>
            tp.kind match
                case Ast.Kind.Alias(underlying) =>
                    val rhs = Parser.typeName(underlying).parse[Type].get
                    List(Defn.Type(Nil, Type.Name(tp.name), Nil, rhs, Type.Bounds(None, None)))
                case Ast.Kind.Handle(_, _, _) =>
                    List(Defn.Type(Nil, Type.Name(tp.name), Nil, ptrByte, Type.Bounds(None, None)))
                case Ast.Kind.Enum(values, isBitfield) =>
                    val baseType = if isBitfield then "CInt" else "CUnsignedInt"
                    val typeDef  = Defn.Type(
                      Nil,
                      Type.Name(tp.name),
                      Nil,
                      Type.Name(baseType),
                      Type.Bounds(None, None)
                    )
                    val valStats: List[Stat] = values.sortBy(_.index).map { v =>
                        val rhs: Term =
                            if isBitfield then Lit.Int(v.index)
                            else Term.Select(Lit.Int(v.index), Term.Name("toUInt"))
                        Defn.Val(
                          List(Mod.Final()),
                          List(Pat.Var(Term.Name(v.name))),
                          Some(Type.Name(tp.name)),
                          rhs
                        )
                    }.toList
                    List(typeDef, simpleObject(tp.name, valStats))
                case Ast.Kind.Struct(_) =>
                    List(Defn.Type(Nil, Type.Name(tp.name), Nil, ptrByte, Type.Bounds(None, None)))
                case Ast.Kind.Function(args, ret) =>
                    List(functionDefStat(tp.name, Ast.Kind.Function(args, ret)))
            end match
        }.toList

        val printed = buildSource(
          "net.`julian-avar`.gdext.generated.types",
          List(
            "import scala.scalanative.unsafe.*",
            "import scala.scalanative.unsigned.*",
            "import scala.scalanative.unsigned.UInt.*"
          ),
          stats
        )
        "// Generated by gdext generator — do not edit.\n" + injectComments(printed, markers)
    end typesSource
end TypesGenerator
